@echo off
cd /d "c:\-Movie-Recommender-System-main"
echo Checking python virtual environment...
if not exist venv (
    echo Creating virtual environment...
    python -m venv venv
)
echo Activating virtual environment...
call venv\Scripts\activate
echo Installing/verifying dependencies...
pip install -r requirements.txt
echo Starting Movie Recommender app on port 8502...
streamlit run app.py --server.port 8502
pause
